
import React from "react";
import { ExternalLink } from "lucide-react";

interface Publication {
  title: string;
  conference: string;
  year: string;
  abstract: string;
  link: string;
  delay: number;
}

const PublicationCard = ({ publication }: { publication: Publication }) => (
  <div 
    className="publication-card animate-fade-in" 
    style={{ animationDelay: `${publication.delay}s` }}
  >
    <h3 className="text-xl font-semibold mb-2">{publication.title}</h3>
    <p className="text-primary font-medium mb-2">{publication.conference}, {publication.year}</p>
    <p className="text-muted-foreground mb-4">{publication.abstract}</p>
    <a 
      href={publication.link}
      target="_blank"
      rel="noopener noreferrer"
      className="inline-flex items-center gap-2 text-primary hover:text-primary/80 font-medium"
    >
      View Publication <ExternalLink size={14} />
    </a>
  </div>
);

const Publications = () => {
  const publications: Publication[] = [
    {
      title: "Mirror Minds: An Empirical Study on Detecting LLM-Generated Text via LLMs",
      conference: "COLING",
      year: "2025",
      abstract: "This paper presents novel techniques to identify text generated by large language models through linguistic pattern analysis and deep learning methods, achieving 95% accuracy across multiple LLM architectures.",
      link: "https://aclanthology.org/2025.genaidetect-1.3/",
      delay: 0
    },
    {
      title: "Advancements in Underwater Image Enhancement Techniques using UFPN-ESRGAN",
      conference: "ICCCNT",
      year: "2024",
      abstract: "We propose a new architecture combining U-Net Feature Pyramid Networks with Enhanced Super-Resolution GANs to significantly improve underwater image clarity while preserving natural color characteristics.",
      link: "https://ieeexplore.ieee.org/document/10724906",
      delay: 0.2
    },
    {
      title: "Machine Learning Techniques for Fake News Detection in Low-Resource Hindi Language: A Comparative Study",
      conference: "ICCCNT",
      year: "2023",
      abstract: "This research introduces a hybrid approach combining linguistic features and content analysis to detect misinformation in Hindi news media, addressing language-specific challenges in fake news detection.",
      link: "https://ieeexplore.ieee.org/document/10307399",
      delay: 0.4
    }
  ];

  return (
    <section id="publications" className="section bg-muted/10">
      <div className="container mx-auto">
        <h2 className="text-3xl md:text-4xl font-bold mb-12 text-center">Publications</h2>
        
        <div className="space-y-6 max-w-4xl mx-auto">
          {publications.map((publication, index) => (
            <PublicationCard key={index} publication={publication} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Publications;
